# New MQTT Binary Sensor Format
mqtt:
  binary_sensor:
  - name: "Sean Garage"
    state_topic: "doors/garage/Sean"
    payload_on: "Open"
    payload_off: "Closed"
    device_class: garage_door
  
  - name: "Erica Garage"
    state_topic: "doors/garage/Erica"
    payload_on: "Open"
    payload_off: "Closed"
    device_class: garage_door
